name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

# 最小权限
permissions:
  contents: read

# 同一分支重复触发时自动取消旧任务
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22]

    steps:
      # actions/checkout v5.0.0 — https://github.com/actions/checkout/releases/tag/v5.0.0
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      # actions/setup-node v4（commit 页面如下）
      # https://github.com/actions/setup-node/commit/a0853c24544627f65ddf259abe73b1d18a591444
- name: Setup Node.js
  uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
  with:
    node-version: ${{ matrix.node-version }}
    cache: npm
    cache-dependency-path: '**/package-lock.json'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present

      # actions/upload-artifact v4（commit 页面如下）
      # https://github.com/actions/upload-artifact/commit/ea165f8d65b6e75b540449e92b4886f43607fa02
      - name: Upload logs & coverage
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: logs-${{ matrix.node-version }}
          path: |
            npm-debug.log
            coverage/**
