@'
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      # checkout（固定到你拿到的 v5 提交 SHA）
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fe910a37f88322edcfb5dd907a8

      # Node（先不启用 cache，等跑绿了再加）
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present

      # 上传日志（即使没有文件也不算失败）
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: logs-${{ matrix.node-version }}
          if-no-files-found: ignore
          path: |
            npm-debug.log
            coverage/**
'@ | Set-Content -Path .github\workflows\ci.yml -Encoding utf8

git add .github\workflows\ci.yml
git commit -m "ci: simplify workflow (disable cache, ignore missing artifacts)"
git pull --rebase --autostash origin main
git push origin main
